server:
  prot:9998

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://59.110.235.86:3306/ssm?useunicode=true;&characterEncoding=utf8
    data-username: root
    data-password: root
